import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bot, Check, MessageSquareReply, Send, UserRoundCheck } from "lucide-react";
import { api } from "../api/client";
import { EmptyState, ErrorState, LoadingState } from "../components/States";
import { StatusBadge } from "../components/StatusBadge";

type Conversation = Record<string, unknown> & { id: number; conversation_uid: string; status: string; channel: string; priority: string };
type Detail = Conversation & { contact: Record<string, unknown>; state: Record<string, unknown>; messages: Array<Record<string, unknown> & { id: number; message_uid: string; direction: string; text?: string; status: string }>; handoff?: Record<string, unknown> };
export default function ConversationsPage() {
  const client = useQueryClient(); const [selectedId, setSelectedId] = useState<string>(); const [draft, setDraft] = useState("");
  const conversations = useQuery({ queryKey: ["conversations"], queryFn: () => api<Conversation[]>("/conversations?limit=100"), refetchInterval: 15000 });
  useEffect(() => { if (!selectedId && conversations.data?.[0]) setSelectedId(conversations.data[0].conversation_uid); }, [conversations.data, selectedId]);
  const detail = useQuery({ queryKey: ["conversation", selectedId], queryFn: () => api<Detail>(`/conversations/${selectedId}`), enabled: !!selectedId, refetchInterval: 15000 });
  const refresh = () => { client.invalidateQueries({ queryKey: ["conversation", selectedId] }); client.invalidateQueries({ queryKey: ["conversations"] }); };
  const approve = useMutation({ mutationFn: (messageId: number) => api(`/messages/${messageId}/approve`, { method: "POST", body: JSON.stringify({ approved_by: "local_operator" }) }), onSuccess: refresh });
  const send = useMutation({ mutationFn: (messageId: number) => api(`/messages/${messageId}/send`, { method: "POST", body: JSON.stringify({ actor: "local_operator" }) }), onSuccess: refresh });
  const reply = useMutation({ mutationFn: () => api(`/conversations/${selectedId}/reply`, { method: "POST", body: JSON.stringify({ text: draft, actor: "local_operator", auto_send: false }) }), onSuccess: () => { setDraft(""); refresh(); } });
  if (conversations.isLoading) return <LoadingState />; if (conversations.isError) return <ErrorState error={conversations.error} retry={() => conversations.refetch()} />;
  return <section className="page conversation-page"><header className="page-header"><div><span className="eyebrow">Customer operations</span><h1>Conversation inbox</h1><p>Human review, grounded AI drafts, customer context, assignment, and follow-ups.</p></div></header>
    {!conversations.data?.length ? <div className="panel"><EmptyState title="No conversations" detail="Inbound channels have not produced a conversation yet." /></div> : <div className="conversation-layout"><aside className="conversation-list"><header><h2>Inbox</h2><span>{conversations.data.length}</span></header>{conversations.data.map((item) => <button key={item.conversation_uid} className={selectedId === item.conversation_uid ? "active" : ""} onClick={() => setSelectedId(item.conversation_uid)}><div><strong>{String(item.conversation_uid)}</strong><StatusBadge value={item.priority} /></div><p>{item.channel} · {item.status}</p><small>{item.assigned_to ? `Assigned: ${String(item.assigned_to)}` : "Unassigned"}</small></button>)}</aside>
      <main className="thread-panel">{detail.isError ? <ErrorState error={detail.error} /> : !selectedId || detail.isLoading || !detail.data ? <LoadingState /> : <><header><div><h2>{detail.data.conversation_uid}</h2><p>{detail.data.channel} · {detail.data.status}</p></div><StatusBadge value={detail.data.status} /></header><div className="message-thread">{detail.data.messages.map((message) => <article key={message.message_uid} className={`message ${String(message.direction).toLowerCase()}`}><div className="message-meta">{message.direction === "OUTBOUND" ? <Bot /> : <MessageSquareReply />}<span>{message.direction}</span><StatusBadge value={message.status} /></div><p>{message.text || "Attachment / event"}</p>{["DRAFT", "PENDING_REVIEW", "APPROVED"].includes(message.status) && <div className="message-actions">{message.status !== "APPROVED" && <button className="button secondary" onClick={() => approve.mutate(message.id)}><Check size={15} />Approve</button>}<button className="button primary" disabled={message.status !== "APPROVED" || send.isPending} onClick={() => send.mutate(message.id)}><Send size={15} />Send</button><details><summary>Why this answer?</summary><p>Open provenance is retained by the backend decision record. Approval is required before a held draft can enter the outbound queue.</p></details></div>}</article>)}</div><form className="reply-composer" onSubmit={(e) => { e.preventDefault(); if (draft.trim()) reply.mutate(); }}><textarea aria-label="Reply draft" value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="Write a human-reviewed response…" /><button className="button primary" disabled={!draft.trim() || reply.isPending}><Send size={16} />Save draft</button></form></>}</main>
      <aside className="context-panel">{detail.data && <><span className="eyebrow">Customer context</span><h2>{String(detail.data.contact.display_name || detail.data.contact.contact_uid)}</h2><dl><div><dt>Customer</dt><dd>{String(detail.data.customer_id || "Unknown contact")}</dd></div><div><dt>Lead</dt><dd>{String(detail.data.lead_uid || "—")}</dd></div><div><dt>Intent</dt><dd>{String(detail.data.state.current_intent || "—")}</dd></div><div><dt>Pending action</dt><dd>{String(detail.data.state.pending_action || "—")}</dd></div></dl>{detail.data.handoff && <div className="handoff-card"><UserRoundCheck /><div><strong>Human handoff</strong><p>{String(detail.data.handoff.reason)}</p><StatusBadge value={detail.data.handoff.priority} /></div></div>}<button className="button secondary full">Assign / handoff</button><button className="button ghost full">Schedule follow-up</button></>}</aside></div>}
  </section>;
}
