import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, FileUp, Pause, Play, RefreshCw, Search, ShieldCheck, UserCheck, UsersRound, XCircle } from "lucide-react";
import { creatorDiscoveryApi } from "../api/creatorDiscovery";
import { DetailDrawer } from "../components/DetailDrawer";
import { EmptyState, ErrorState, LoadingState } from "../components/States";
import { StatusBadge } from "../components/StatusBadge";
import type { Candidate, CreatorDetail, CreatorSummary, DiscoveryPlatform, DiscoveryRequest, DiscoveryRun } from "../types/creatorDiscovery";

const platforms: DiscoveryPlatform[] = ["youtube", "facebook", "instagram", "tiktok", "snapchat", "linkedin", "x"];
const tabs = ["New Discovery", "Runs", "Review Matches", "Creators", "Connections", "Export"] as const;

function message(error: unknown) { return error instanceof Error ? error.message : "Request failed"; }
function percent(value: number) { return `${Math.round(value)}%`; }
type ProfileEdits = { niche: string; industry: string; main_platform: string; content_mechanism_style: string; kpi_impact: string; start_year: string };

export default function CreatorDiscoveryPage() {
  const client = useQueryClient();
  const [tab, setTab] = useState<(typeof tabs)[number]>("New Discovery");
  const [names, setNames] = useState("");
  const [selectedPlatforms, setSelectedPlatforms] = useState<DiscoveryPlatform[]>(["youtube", "facebook", "instagram", "tiktok"]);
  const [analyze, setAnalyze] = useState(true); const [resolve, setResolve] = useState(true); const [updateExisting, setUpdateExisting] = useState(false);
  const [sampleSize, setSampleSize] = useState(10); const [inputFile, setInputFile] = useState<File>();
  const [selectedRun, setSelectedRun] = useState<DiscoveryRun>(); const [selectedCreator, setSelectedCreator] = useState<CreatorSummary>();
  const [selectedCandidate, setSelectedCandidate] = useState<Candidate>(); const [mergeUid, setMergeUid] = useState("");
  const [candidateOffset, setCandidateOffset] = useState(0); const [creatorOffset, setCreatorOffset] = useState(0);
  const [query, setQuery] = useState(""); const [platformFilter, setPlatformFilter] = useState(""); const [industryFilter, setIndustryFilter] = useState("");
  const [nicheFilter, setNicheFilter] = useState(""); const [influenceMin, setInfluenceMin] = useState(""); const [confidenceMin, setConfidenceMin] = useState("");
  const [analysisFilter, setAnalysisFilter] = useState(""); const [startYear, setStartYear] = useState("");
  const [profileEdits, setProfileEdits] = useState<ProfileEdits>({ niche: "", industry: "", main_platform: "", content_mechanism_style: "", kpi_impact: "", start_year: "" });

  const connectors = useQuery({ queryKey: ["creator-discovery", "connectors"], queryFn: creatorDiscoveryApi.connectors });
  const industries = useQuery({ queryKey: ["creator-discovery", "industries"], queryFn: creatorDiscoveryApi.industries });
  const runs = useQuery({ queryKey: ["creator-discovery", "runs"], queryFn: () => creatorDiscoveryApi.runs(), enabled: tab === "Runs", refetchInterval: tab === "Runs" ? 5000 : false });
  const candidates = useQuery({ queryKey: ["creator-discovery", "candidates", candidateOffset], queryFn: () => creatorDiscoveryApi.candidates(candidateOffset), enabled: tab === "Review Matches" });
  const creatorParams = useMemo(() => { const values = new URLSearchParams({ offset: String(creatorOffset), limit: "50" });
    if (query) values.set("q", query); if (platformFilter) values.set("platform", platformFilter); if (industryFilter) values.set("industry", industryFilter);
    if (nicheFilter) values.set("niche", nicheFilter); if (influenceMin) values.set("influence_min", influenceMin); if (confidenceMin) values.set("match_confidence_min", confidenceMin);
    if (analysisFilter) values.set("analysis_status", analysisFilter); if (startYear) values.set("start_year", startYear); return values;
  }, [creatorOffset, query, platformFilter, industryFilter, nicheFilter, influenceMin, confidenceMin, analysisFilter, startYear]);
  const creators = useQuery({ queryKey: ["creator-discovery", "creators", creatorParams.toString()], queryFn: () => creatorDiscoveryApi.creators(creatorParams), enabled: tab === "Creators" });
  const detail = useQuery({ queryKey: ["creator-discovery", "creator", selectedCreator?.profile_uid], queryFn: () => creatorDiscoveryApi.creator(selectedCreator!.profile_uid), enabled: Boolean(selectedCreator) });
  const metaStatus = useQuery({ queryKey: ["creator-discovery", "meta-status"], queryFn: creatorDiscoveryApi.metaStatus, enabled: tab === "Connections" });

  const request = (): DiscoveryRequest => ({ inputs: names.split(/\r?\n/).map((value) => value.trim()).filter(Boolean), platforms: selectedPlatforms, analyze_content: analyze, resolve_cross_platform_identity: resolve, update_existing_profiles: updateExisting, content_sample_size: sampleSize, execute: true });
  const create = useMutation({ mutationFn: () => creatorDiscoveryApi.createRun(request()), onSuccess: (run) => { setSelectedRun(run); setTab("Runs"); client.invalidateQueries({ queryKey: ["creator-discovery"] }); } });
  const importRun = useMutation({ mutationFn: () => { const { inputs: _inputs, ...options } = request(); return creatorDiscoveryApi.importRun(inputFile!, options); }, onSuccess: (run) => { setSelectedRun(run); setTab("Runs"); client.invalidateQueries({ queryKey: ["creator-discovery"] }); } });
  const runAction = useMutation({ mutationFn: ({ uid, action }: { uid: string; action: "pause" | "resume" | "retry" | "cancel" }) => creatorDiscoveryApi.runAction(uid, action), onSuccess: (run) => { setSelectedRun(run); client.invalidateQueries({ queryKey: ["creator-discovery", "runs"] }); } });
  const review = useMutation({ mutationFn: async ({ candidate, action }: { candidate: Candidate; action: "THIS_IS_THE_ACCOUNT" | "MERGE" | "KEEP_SEPARATE" | "REJECT" }) => { if (action === "REJECT") await creatorDiscoveryApi.reject(candidate.candidate_uid); else await creatorDiscoveryApi.confirm(candidate.candidate_uid, action, mergeUid); }, onSuccess: () => { setSelectedCandidate(undefined); setMergeUid(""); client.invalidateQueries({ queryKey: ["creator-discovery"] }); } });
  const refresh = useMutation({ mutationFn: (uid: string) => creatorDiscoveryApi.refresh(uid), onSuccess: (value: CreatorDetail) => { setSelectedCreator(value.unified_profile); client.invalidateQueries({ queryKey: ["creator-discovery", "creators"] }); client.invalidateQueries({ queryKey: ["creator-discovery", "creator"] }); } });
  const saveProfile = useMutation({ mutationFn: () => creatorDiscoveryApi.updateCreator(selectedCreator!.profile_uid, {
    niche: profileEdits.niche, industry: profileEdits.industry, main_platform: profileEdits.main_platform || null,
    content_mechanism_style: profileEdits.content_mechanism_style, kpi_impact: profileEdits.kpi_impact,
    start_year: profileEdits.start_year ? Number(profileEdits.start_year) : null,
  }), onSuccess: (value) => { setSelectedCreator(value.unified_profile); client.invalidateQueries({ queryKey: ["creator-discovery", "creators"] }); client.invalidateQueries({ queryKey: ["creator-discovery", "creator"] }); } });
  const exportData = useMutation({ mutationFn: ({ format, extended }: { format: "csv" | "xlsx"; extended: boolean }) => creatorDiscoveryApi.export(format, extended) });
  const validateMeta = useMutation({ mutationFn: creatorDiscoveryApi.validateMeta, onSuccess: (value) => { client.setQueryData(["creator-discovery", "meta-status"], value); client.invalidateQueries({ queryKey: ["creator-discovery", "connectors"] }); } });

  function togglePlatform(platform: DiscoveryPlatform) { setSelectedPlatforms((current) => current.includes(platform) ? current.filter((item) => item !== platform) : [...current, platform]); }
  function openCreator(creator: CreatorSummary) { setSelectedCreator(creator); setProfileEdits({ niche: creator.niche, industry: creator.industry, main_platform: creator.main_platform === "UNKNOWN" ? "" : creator.main_platform, content_mechanism_style: creator.content_mechanism_style, kpi_impact: creator.kpi_impact, start_year: creator.start_year ? String(creator.start_year) : "" }); }

  return <section className="page creator-discovery-page">
    <header className="page-header hero"><div><span className="eyebrow">Public identity and content evidence</span><h1>Creator Discovery</h1><p>Discover public accounts across selected platforms, review identity matches, retain provenance, and build unified creator profiles without silent merges.</p></div><StatusBadge value="COMPLIANT_PUBLIC_ONLY" /></header>
    <div className="tabbar" role="tablist">{tabs.map((item) => <button key={item} role="tab" aria-selected={tab === item} onClick={() => setTab(item)}>{item}</button>)}</div>

    {tab === "New Discovery" && <div className="discovery-builder">
      <section className="panel discovery-form"><div className="panel-heading"><div><span className="eyebrow">Names or direct profile URLs</span><h2>New Discovery</h2></div><UsersRound /></div>
        <label>Creator Name(s)<textarea aria-label="Creator Name(s)" rows={8} value={names} onChange={(event) => setNames(event.target.value)} placeholder={"Ahmed Example\nhttps://www.youtube.com/@example"} /></label>
        <fieldset className="lead-checklist"><legend>Platforms</legend><div>{platforms.map((platform) => <label key={platform}><input type="checkbox" checked={selectedPlatforms.includes(platform)} onChange={() => togglePlatform(platform)} /><span><strong>{platform === "x" ? "X" : platform[0].toUpperCase() + platform.slice(1)}</strong><small>{connectors.data?.find((item) => item.platform === platform)?.name_discovery || "Checking capability…"}</small></span></label>)}</div></fieldset>
        <div className="discovery-options"><label><input type="checkbox" checked={analyze} onChange={(event) => setAnalyze(event.target.checked)} />Analyze Content</label><label><input type="checkbox" checked={resolve} onChange={(event) => setResolve(event.target.checked)} />Resolve Cross-Platform Identity</label><label><input type="checkbox" checked={updateExisting} onChange={(event) => setUpdateExisting(event.target.checked)} />Update Existing Profiles</label><label>Content Sample Size<input aria-label="Content Sample Size" type="number" min={1} max={30} value={sampleSize} onChange={(event) => setSampleSize(Number(event.target.value))} /></label></div>
        <div className="run-actions"><button className="button primary" disabled={!names.trim() || !selectedPlatforms.length || create.isPending} onClick={() => create.mutate()}><Play size={16} />START DISCOVERY</button><label className="button secondary file-action"><FileUp size={16} />CSV / XLSX<input aria-label="Creator input file" hidden type="file" accept=".csv,.xlsx" onChange={(event) => setInputFile(event.target.files?.[0])} /></label><button className="button secondary" disabled={!inputFile || !selectedPlatforms.length || importRun.isPending} onClick={() => importRun.mutate()}>Import {inputFile?.name || "file"}</button></div>
        {(create.isError || importRun.isError) && <p className="inline-error">{message(create.error || importRun.error)}</p>}
      </section>
      <section className="panel capability-panel"><div className="panel-heading"><div><span className="eyebrow">No fake availability</span><h2>Connector capabilities</h2></div><ShieldCheck /></div>{connectors.isLoading ? <LoadingState /> : connectors.isError ? <ErrorState error={connectors.error} retry={() => connectors.refetch()} /> : connectors.data?.map((item) => <article key={item.platform}><div><strong>{item.platform}</strong><small>{item.detail}</small></div><StatusBadge value={item.configured ? "CONFIGURED" : item.name_discovery} /><dl><div><dt>Direct URL</dt><dd>{item.direct_url}</dd></div><div><dt>Sampling</dt><dd>{item.content_sampling}</dd></div></dl></article>)}</section>
    </div>}

    {tab === "Runs" && <div className="runs-layout"><section className="panel run-list"><div className="panel-heading"><h2>Discovery runs</h2></div>{runs.isLoading ? <LoadingState /> : runs.data?.items.length ? runs.data.items.map((run) => <button key={run.run_uid} className={selectedRun?.run_uid === run.run_uid ? "active" : ""} onClick={() => setSelectedRun(run)}><div><strong>{run.run_uid}</strong><StatusBadge value={run.status} /></div><span>{run.input_count} inputs · {run.platforms.join(", ")}</span></button>) : <EmptyState title="No discovery runs" />}</section>
      <section className="panel">{selectedRun ? <><div className="panel-heading"><div><span className="eyebrow">Checkpointed run</span><h2>{selectedRun.run_uid}</h2></div><StatusBadge value={selectedRun.status} /></div><div className="progress-body"><div className="progress-track"><i style={{ width: `${selectedRun.input_count ? selectedRun.processed / selectedRun.input_count * 100 : 0}%` }} /></div><strong>{selectedRun.processed}/{selectedRun.input_count}</strong><dl><div><dt>Matched candidates</dt><dd>{selectedRun.matched}</dd></div><div><dt>Review required</dt><dd>{selectedRun.review_required}</dd></div><div><dt>Failed</dt><dd>{selectedRun.failed}</dd></div><div><dt>Status</dt><dd>{selectedRun.status}</dd></div></dl></div><div className="run-controls"><button className="button secondary" onClick={() => runAction.mutate({ uid: selectedRun.run_uid, action: "pause" })}><Pause size={15} />Pause</button><button className="button secondary" onClick={() => runAction.mutate({ uid: selectedRun.run_uid, action: "resume" })}><Play size={15} />Resume</button><button className="button secondary" onClick={() => runAction.mutate({ uid: selectedRun.run_uid, action: "retry" })}><RefreshCw size={15} />Retry Failed</button><button className="button ghost" onClick={() => runAction.mutate({ uid: selectedRun.run_uid, action: "cancel" })}><XCircle size={15} />Cancel</button></div><div className="job-table"><table><thead><tr><th>Input</th><th>Status</th><th>Candidates</th><th>Attempt</th></tr></thead><tbody>{selectedRun.jobs.map((job) => <tr key={job.job_uid}><td>{job.input_value}</td><td><StatusBadge value={job.status} /></td><td>{job.candidate_count}</td><td>{job.attempt}</td></tr>)}</tbody></table></div></> : <EmptyState title="Select a run" />}</section></div>}

    {tab === "Review Matches" && <section className="panel review-panel">
      <div className="panel-heading"><div><span className="eyebrow">Human identity resolution</span><h2>Review Matches</h2></div><StatusBadge value={`${candidates.data?.total || 0}_PENDING`} /></div>
      {candidates.isLoading ? <LoadingState /> : candidates.isError ? <ErrorState error={candidates.error} retry={() => candidates.refetch()} /> : candidates.data?.items.length ? <div className="candidate-grid">{candidates.data.items.map((candidate) => <article key={candidate.candidate_uid} className={selectedCandidate?.candidate_uid === candidate.candidate_uid ? "selected" : ""} onClick={() => setSelectedCandidate(candidate)}>
        <header><div><strong>{candidate.display_name || candidate.username || "UNKNOWN"}</strong><a href={candidate.profile_url} target="_blank" rel="noreferrer">{candidate.platform}</a></div><span className="confidence">{percent(candidate.confidence)}</span></header>
        <p>{candidate.public_bio || "No public bio collected."}</p>
        <div className="candidate-signals"><StatusBadge value={candidate.classification} /><StatusBadge value={candidate.data_collection_status} /><span>Data {percent(candidate.data_completeness)}</span><span>{candidate.followers == null ? "followers NOT_AVAILABLE" : `${candidate.followers.toLocaleString()} followers`}</span><span>{candidate.connector_requirement}</span></div>
        <footer><button className="button primary" onClick={(event) => { event.stopPropagation(); review.mutate({ candidate, action: "THIS_IS_THE_ACCOUNT" }); }}><UserCheck size={14} />THIS IS THE ACCOUNT</button><button className="button secondary" onClick={(event) => { event.stopPropagation(); review.mutate({ candidate, action: "KEEP_SEPARATE" }); }}>KEEP SEPARATE</button><button className="button ghost" onClick={(event) => { event.stopPropagation(); review.mutate({ candidate, action: "REJECT" }); }}>NOT THIS ACCOUNT</button></footer>
        {selectedCandidate?.candidate_uid === candidate.candidate_uid && <div className="merge-row"><input aria-label="Creator UID to merge" placeholder="Existing creator UID" value={mergeUid} onChange={(event) => setMergeUid(event.target.value)} /><button className="button secondary" disabled={!mergeUid} onClick={(event) => { event.stopPropagation(); review.mutate({ candidate, action: "MERGE" }); }}>MERGE</button><pre>{JSON.stringify({ identity_status: candidate.identity_status, data_collection_status: candidate.data_collection_status, data_completeness: candidate.data_completeness, connector_requirement: candidate.connector_requirement, profile_data: candidate.profile_data, provenance: candidate.provenance }, null, 2)}</pre></div>}
      </article>)}</div> : <EmptyState title="No pending matches" />}
      {candidates.data && <div className="pagination"><span>{candidates.data.total} pending candidates</span><div><button disabled={!candidateOffset} onClick={() => setCandidateOffset(Math.max(0, candidateOffset - 50))}>Previous</button><button disabled={candidateOffset + 50 >= candidates.data.total} onClick={() => setCandidateOffset(candidateOffset + 50)}>Next</button></div></div>}{review.isError && <p className="inline-error">{message(review.error)}</p>}
    </section>}

    {tab === "Creators" && <section className="panel results-panel">
      <div className="panel-heading"><div><span className="eyebrow">Server-paginated unified profiles</span><h2>Creators</h2></div></div>
      <div className="creator-filters"><label><Search size={15} /><input aria-label="Creator search" placeholder="Name or UID" value={query} onChange={(event) => { setQuery(event.target.value); setCreatorOffset(0); }} /></label><select aria-label="Platform filter" value={platformFilter} onChange={(event) => setPlatformFilter(event.target.value)}><option value="">All platforms</option>{platforms.map((item) => <option key={item} value={item}>{item}</option>)}</select><select aria-label="Industry filter" value={industryFilter} onChange={(event) => setIndustryFilter(event.target.value)}><option value="">All industries</option>{industries.data?.map((item) => <option key={item.code} value={item.name}>{item.name}</option>)}</select><input aria-label="Niche filter" placeholder="Niche" value={nicheFilter} onChange={(event) => setNicheFilter(event.target.value)} /><input aria-label="Minimum influence" type="number" min="0" placeholder="Min followers" value={influenceMin} onChange={(event) => setInfluenceMin(event.target.value)} /><input aria-label="Minimum match confidence" type="number" min="0" max="100" placeholder="Min confidence" value={confidenceMin} onChange={(event) => setConfidenceMin(event.target.value)} /><select aria-label="Analysis status filter" value={analysisFilter} onChange={(event) => setAnalysisFilter(event.target.value)}><option value="">All analysis</option><option>COMPLETED</option><option>ANALYSIS_READY</option><option>API_REQUIRED</option><option>COLLECTION_PENDING</option><option>IDENTITY_ONLY</option><option>INSUFFICIENT_EVIDENCE</option></select><input aria-label="Start year filter" type="number" min="1900" max="2100" placeholder="Start year" value={startYear} onChange={(event) => setStartYear(event.target.value)} /></div>
      {creators.isLoading ? <LoadingState /> : creators.isError ? <ErrorState error={creators.error} retry={() => creators.refetch()} /> : creators.data?.items.length ? <div className="table-wrap"><table><thead><tr><th>Name</th><th>Niche</th><th>Industry</th><th>Main Platform</th><th>Platforms Found</th><th>Influence Size</th><th>Match Confidence</th><th>Data Completeness</th><th>Analysis Status</th><th>Last Updated</th></tr></thead><tbody>{creators.data.items.map((creator) => <tr key={creator.profile_uid} tabIndex={0} onClick={() => openCreator(creator)} onKeyDown={(event) => event.key === "Enter" && openCreator(creator)}><td>{creator.name}</td><td>{creator.niche}</td><td>{creator.industry}</td><td>{creator.main_platform}</td><td>{creator.platforms_found.join(", ")}</td><td>{creator.influence_size}</td><td>{percent(creator.match_confidence)}</td><td>{percent(creator.data_completeness)}</td><td><StatusBadge value={creator.analysis_status} /></td><td>{new Date(creator.updated_at).toLocaleDateString()}</td></tr>)}</tbody></table><div className="pagination"><span>{creators.data.total} profiles</span><div><button disabled={!creatorOffset} onClick={() => setCreatorOffset(Math.max(0, creatorOffset - 50))}>Previous</button><button disabled={creatorOffset + 50 >= creators.data.total} onClick={() => setCreatorOffset(creatorOffset + 50)}>Next</button></div></div></div> : <EmptyState title="No unified creators" />}
    </section>}

    {tab === "Connections" && <section className="panel meta-settings">
      <div className="panel-heading"><div><span className="eyebrow">Backend-only credentials</span><h2>Meta / Instagram / Facebook</h2></div><ShieldCheck /></div>
      {metaStatus.isLoading ? <LoadingState /> : metaStatus.isError ? <ErrorState error={metaStatus.error} retry={() => metaStatus.refetch()} /> : metaStatus.data && <>
        <div className="meta-config-grid">
          <div><span>App ID configured</span><strong>{metaStatus.data.app_id_configured ? "YES" : "NO"}</strong></div>
          <div><span>App Secret configured</span><strong>{metaStatus.data.app_secret_configured ? "YES" : "NO"}</strong></div>
          <div><span>Access Token configured</span><strong>{metaStatus.data.access_token_configured ? "YES" : "NO"}</strong><small>{metaStatus.data.token_hint || ""}</small></div>
          <div><span>Graph API</span><strong>{metaStatus.data.graph_api_version}</strong></div>
        </div>
        <div className="meta-platforms">
          {(["instagram", "facebook"] as const).map((platform) => <article key={platform}><header><strong>{platform[0].toUpperCase() + platform.slice(1)}</strong><StatusBadge value={metaStatus.data![platform].status} /></header><p>{metaStatus.data![platform].message}</p><small>Account linked: {metaStatus.data![platform].account_configured ? "YES" : "NO"}</small>{metaStatus.data![platform].missing_permissions.length > 0 && <small>Missing: {metaStatus.data![platform].missing_permissions.join(", ")}</small>}</article>)}
        </div>
        <p className="meta-validation-time">Last validation: {new Date(metaStatus.data.last_validation).toLocaleString()}</p>
        <button className="button primary" disabled={validateMeta.isPending} onClick={() => validateMeta.mutate()}><ShieldCheck size={15} />VALIDATE CONNECTION</button>
      </>}
      {validateMeta.isError && <p className="inline-error">{message(validateMeta.error)}</p>}
    </section>}

    {tab === "Export" && <section className="panel export-studio"><Download /><h2>Workbook-compatible export</h2><p>Standard XLSX contains EGYPT_MASSIVE_DUMP and INDUSTRY_SUMMARY with the reference columns. X appears only in an explicitly extended export.</p><div><button className="button primary" onClick={() => exportData.mutate({ format: "xlsx", extended: false })}>Standard XLSX</button><button className="button secondary" onClick={() => exportData.mutate({ format: "xlsx", extended: true })}>Extended XLSX + X</button><button className="button secondary" onClick={() => exportData.mutate({ format: "csv", extended: false })}>CSV</button></div>{exportData.isError && <p className="inline-error">{message(exportData.error)}</p>}</section>}

    <DetailDrawer item={detail.data?.unified_profile as unknown as Record<string, unknown> | undefined} title={selectedCreator?.creator_uid || "Creator detail"} onClose={() => setSelectedCreator(undefined)}>
      {detail.isLoading ? <LoadingState /> : detail.data && <div className="creator-detail-sections">
        <h3>Unified Profile</h3>
        <div className="creator-collection-status">
          <div><span>Identity Match</span><strong>{detail.data.identity_match?.status || detail.data.unified_profile.identity_status}</strong></div>
          <div><span>Data Collection</span><strong>{detail.data.unified_profile.data_collection_status}</strong></div>
          <div><span>Data Completeness</span><strong>{percent(detail.data.unified_profile.data_completeness)}</strong></div>
          <div><span>Content Samples</span><strong>{detail.data.content_samples.length}</strong></div>
          <div><span>Analysis Status</span><strong>{detail.data.unified_profile.analysis_status}</strong></div>
          <div><span>Last API Refresh</span><strong>{detail.data.last_api_refresh ? new Date(detail.data.last_api_refresh).toLocaleString() : "NOT_RUN"}</strong></div>
          <div><span>API Requirement / Permission</span><strong>{detail.data.api_requirement_problem || "NONE"}</strong></div>
          <div><span>Meta Connector</span><strong>Instagram {detail.data.meta_connector_status?.instagram.status || "UNKNOWN"} / Facebook {detail.data.meta_connector_status?.facebook.status || "UNKNOWN"}</strong></div>
        </div>
        <form className="profile-corrections" onSubmit={(event) => { event.preventDefault(); saveProfile.mutate(); }}><label>Niche<input aria-label="Edit niche" value={profileEdits.niche} onChange={(event) => setProfileEdits({ ...profileEdits, niche: event.target.value })} /></label><label>Industry<select aria-label="Edit industry" value={profileEdits.industry} onChange={(event) => setProfileEdits({ ...profileEdits, industry: event.target.value })}><option value="UNKNOWN">UNKNOWN</option>{industries.data?.map((item) => <option key={item.code} value={item.name}>{item.name}</option>)}</select></label><label>Main Platform<select aria-label="Edit main platform" value={profileEdits.main_platform} onChange={(event) => setProfileEdits({ ...profileEdits, main_platform: event.target.value })}><option value="">UNKNOWN</option>{platforms.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label>Start Year<input aria-label="Edit start year" type="number" min="1900" max="2100" value={profileEdits.start_year} onChange={(event) => setProfileEdits({ ...profileEdits, start_year: event.target.value })} /></label><label className="wide">Content Mechanism / Style<textarea aria-label="Edit content style" rows={2} value={profileEdits.content_mechanism_style} onChange={(event) => setProfileEdits({ ...profileEdits, content_mechanism_style: event.target.value })} /></label><label className="wide">KPI Impact<textarea aria-label="Edit KPI impact" rows={2} value={profileEdits.kpi_impact} onChange={(event) => setProfileEdits({ ...profileEdits, kpi_impact: event.target.value })} /></label><button className="button primary" disabled={saveProfile.isPending}>Save manual corrections</button></form>
        {saveProfile.isError && <p className="inline-error">{message(saveProfile.error)}</p>}
        <details open><summary>Platform Accounts ({detail.data.platform_accounts.length})</summary><pre>{JSON.stringify(detail.data.platform_accounts, null, 2)}</pre></details><details><summary>Content Samples ({detail.data.content_samples.length})</summary><pre>{JSON.stringify(detail.data.content_samples, null, 2)}</pre></details><details><summary>Analysis</summary><pre>{JSON.stringify(detail.data.analysis, null, 2)}</pre></details><details><summary>Match Evidence</summary><pre>{JSON.stringify(detail.data.match_evidence, null, 2)}</pre></details><details><summary>Provenance</summary><pre>{JSON.stringify(detail.data.provenance, null, 2)}</pre></details><details><summary>History</summary><pre>{JSON.stringify(detail.data.history, null, 2)}</pre></details>
        <button className="button secondary" disabled={refresh.isPending} onClick={() => refresh.mutate(detail.data!.unified_profile.profile_uid)}><RefreshCw size={15} />Refresh public data</button>
      </div>}
    </DetailDrawer>
  </section>;
}
