import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Ban, CheckCircle2, Eye, Play, RefreshCw, ShieldAlert, WandSparkles } from "lucide-react";
import { api } from "../api/client";
import { operatorApi } from "../api/operator";
import { DataTable } from "../components/DataTable";
import { DetailDrawer } from "../components/DetailDrawer";
import { EmptyState, ErrorState, LoadingState } from "../components/States";
import { StatusBadge } from "../components/StatusBadge";

type Contract = { contract_uid: string; version: number; status: string; recipe_id: number; recipe_version: number; payload: Record<string, unknown>; evaluation_uid: string };
export default function GenerationPage() {
  const [tab, setTab] = useState("jobs"); const [contractId, setContractId] = useState(""); const [type, setType] = useState("copy"); const [contract, setContract] = useState<Contract>(); const [selected, setSelected] = useState<Record<string, unknown>>(); const queryClient = useQueryClient();
  const jobs = useQuery({ queryKey: ["workspace", "generation-jobs"], queryFn: () => operatorApi.workspace("generation-jobs") });
  const providers = useQuery({ queryKey: ["generation-providers"], queryFn: () => api<Record<string, unknown>[]>("/generation/providers"), enabled: tab === "providers" });
  const models = useQuery({ queryKey: ["generation-models"], queryFn: () => api<Record<string, unknown>[]>("/generation/models"), enabled: tab === "providers" });
  const inspect = useMutation({ mutationFn: () => api<Contract>(`/generation-contracts/${encodeURIComponent(contractId)}`), onSuccess: setContract });
  const create = useMutation({ mutationFn: () => api("/generation/jobs", { method: "POST", body: JSON.stringify({ generation_contract_id: contract!.contract_uid, generation_contract_version: contract!.version, generation_type: type, dry_run: false, execute: false }) }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["workspace", "generation-jobs"] }); setTab("jobs"); } });
  const ready = String(contract?.status ?? "").toUpperCase() === "READY";
  return <section className="page"><header className="page-header"><div><span className="eyebrow">Contract-first creation</span><h1>Generation</h1><p>Build and inspect readiness before any model is selected or invoked.</p></div><button className="button secondary" onClick={() => jobs.refetch()}><RefreshCw size={16} />Refresh</button></header>
    <div className="tabbar">{[["jobs", "Jobs"], ["create", "Create"], ["providers", "Providers & models"], ["qa", "QA"]].map(([value, label]) => <button key={value} aria-selected={tab === value} onClick={() => setTab(value)}>{label}</button>)}</div>
    {tab === "jobs" && <div className="panel"><div className="panel-heading"><div><h2>Generation jobs</h2><p>Status, provider, model, attempts, QA, and approval.</p></div></div>{jobs.isLoading ? <LoadingState /> : jobs.isError ? <ErrorState error={jobs.error} /> : jobs.data!.items.length ? <DataTable rows={jobs.data!.items} total={jobs.data!.total} offset={0} limit={50} onPage={() => undefined} onSelect={setSelected} /> : <EmptyState title="No generation jobs yet" action={<button className="button primary" onClick={() => setTab("create")}><WandSparkles size={16} />Create a job</button>} />}</div>}
    {tab === "create" && <div className="generation-workbench"><div className="panel"><span className="eyebrow">Step 1 · Contract</span><h2>Generation contract</h2><label>Contract UID or ID<input value={contractId} onChange={(e) => { setContractId(e.target.value); setContract(undefined); }} placeholder="GCON_…" /></label><label>Output type<select value={type} onChange={(e) => setType(e.target.value)}><option value="copy">Copy</option><option value="image">Image</option><option value="video">Video</option><option value="audio">Audio</option><option value="storyboard">Storyboard</option></select></label><button className="button secondary" disabled={!contractId || inspect.isPending} onClick={() => inspect.mutate()}><Eye size={16} />Inspect readiness</button>{inspect.isError && <ErrorState error={inspect.error} />}</div>
      <div className="panel contract-panel"><span className="eyebrow">Step 2 · Readiness</span>{!contract ? <EmptyState title="No contract selected" detail="Select an immutable backend contract to inspect constraints, evidence, rights, accessibility, and QA requirements." /> : <><div className="contract-status">{ready ? <CheckCircle2 /> : <ShieldAlert />}<div><h2>{contract.contract_uid} · v{contract.version}</h2><StatusBadge value={contract.status} /></div></div><div className="spec-grid"><article><span>Recipe</span><strong>{contract.recipe_id} · v{contract.recipe_version}</strong></article><article><span>Evaluation</span><strong>{contract.evaluation_uid}</strong></article><article><span>Privacy</span><strong>Backend policy</strong></article></div><details><summary>Provider-neutral creative spec & compiled constraints</summary><pre>{JSON.stringify(contract.payload, null, 2)}</pre></details><button className="button primary generate-button" disabled={!ready || create.isPending} onClick={() => create.mutate()}>{ready ? <Play size={17} /> : <Ban size={17} />}{ready ? "Create queued job" : "Generation blocked — contract not READY"}</button></>}</div></div>}
    {tab === "providers" && <div className="split-panels"><div className="panel"><h2>Providers</h2>{providers.isLoading ? <LoadingState /> : providers.data?.length ? <DataTable rows={providers.data} total={providers.data.length} offset={0} limit={100} onPage={() => undefined} onSelect={setSelected} /> : <EmptyState />}</div><div className="panel"><h2>Models</h2>{models.isLoading ? <LoadingState /> : models.data?.length ? <DataTable rows={models.data} total={models.data.length} offset={0} limit={100} onPage={() => undefined} onSelect={setSelected} /> : <EmptyState />}</div></div>}
    {tab === "qa" && <div className="panel"><EmptyState title="No QA records selected" detail="Open a generation job or asset to inspect technical, brand, character, rights, provenance, accessibility, and continuity QA." /></div>}
    <DetailDrawer item={selected} title="Generation detail" onClose={() => setSelected(undefined)} />
  </section>;
}
