import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, Check, Clapperboard, FileImage, Layers3, Play, RefreshCw, Save, Upload, WandSparkles } from "lucide-react";
import { videoStudioApi, type Character, type VideoJob } from "../api/videoStudio";
import { EmptyState, ErrorState, LoadingState } from "../components/States";
import { StatusBadge } from "../components/StatusBadge";

const ratios = ["9:16", "16:9", "1:1", "4:5"];

export default function VideoStudioPage() {
  const client = useQueryClient();
  const [tab, setTab] = useState("studio");
  const [file, setFile] = useState<File>(); const [characterName, setCharacterName] = useState(""); const [identityNotes, setIdentityNotes] = useState("");
  const [characterId, setCharacterId] = useState(""); const [recipeId, setRecipeId] = useState("EMY_CHARACTER_V1"); const [idea, setIdea] = useState("");
  const [duration, setDuration] = useState(5); const [style, setStyle] = useState("premium commercial"); const [camera, setCamera] = useState("gentle cinematic push-in");
  const [ratio, setRatio] = useState("9:16"); const [modelId, setModelId] = useState(""); const [selectedJobId, setSelectedJobId] = useState(""); const [batchIdeas, setBatchIdeas] = useState("");
  const config = useQuery({ queryKey: ["video-studio", "config"], queryFn: videoStudioApi.config });
  const characters = useQuery({ queryKey: ["video-studio", "characters"], queryFn: videoStudioApi.characters });
  const jobs = useQuery({ queryKey: ["video-studio", "jobs"], queryFn: videoStudioApi.jobs, refetchInterval: 2000 });
  useEffect(() => { if (!modelId && config.data) setModelId(config.data.default_model); }, [config.data, modelId]);
  useEffect(() => { if (!characterId && characters.data?.length) setCharacterId(characters.data[0].character_id); }, [characters.data, characterId]);
  useEffect(() => { if (!selectedJobId && jobs.data?.length) setSelectedJobId(jobs.data[0].job_id); }, [jobs.data, selectedJobId]);
  const selectedJob = useMemo(() => jobs.data?.find((item) => item.job_id === selectedJobId), [jobs.data, selectedJobId]);
  const ready = config.data?.generation_available === true;
  const upload = useMutation({ mutationFn: async () => { const form = new FormData(); form.append("file", file!); form.append("name", characterName); form.append("identity_data", JSON.stringify({ notes: identityNotes })); form.append("style_profile", JSON.stringify({ source: "operator_reference" })); form.append("recurring_attributes", JSON.stringify(identityNotes ? [identityNotes] : [])); form.append("negative_constraints", "[]"); return videoStudioApi.uploadCharacter(form); }, onSuccess: (value: Character) => { setCharacterId(value.character_id); setFile(undefined); setCharacterName(""); setIdentityNotes(""); client.invalidateQueries({ queryKey: ["video-studio", "characters"] }); } });
  const generate = useMutation({ mutationFn: () => { if (!config.data?.generation_available) throw new Error("Video generation runtime is not configured"); return videoStudioApi.generate({ character_id: characterId, recipe_id: recipeId, creative_idea: idea, video_duration: duration, style, camera_motion: camera, aspect_ratio: ratio, model_id: modelId, execute: true }); }, onSuccess: (job) => { setSelectedJobId(job.job_id); setTab("progress"); client.invalidateQueries({ queryKey: ["video-studio", "jobs"] }); } });
  const batch = useMutation({ mutationFn: () => { if (!config.data?.generation_available) throw new Error("Video generation runtime is not configured"); return videoStudioApi.batch({ character_id: characterId, recipe_id: recipeId, video_duration: duration, style, camera_motion: camera, aspect_ratio: ratio, model_id: modelId, execute: true, items: batchIdeas.split("\n").map((value) => value.trim()).filter(Boolean).map((value, index) => ({ idea: value, calendar_item_id: `UI-${Date.now()}-${index + 1}` })) }); }, onSuccess: () => { setTab("progress"); setBatchIdeas(""); client.invalidateQueries({ queryKey: ["video-studio", "jobs"] }); } });
  const retry = useMutation({ mutationFn: (jobId: string) => videoStudioApi.retry(jobId), onSuccess: () => client.invalidateQueries({ queryKey: ["video-studio", "jobs"] }) });
  const save = useMutation({ mutationFn: (assetId: string) => videoStudioApi.save(assetId), onSuccess: () => client.invalidateQueries({ queryKey: ["video-studio", "jobs"] }) });
  if (config.isLoading || characters.isLoading || jobs.isLoading) return <LoadingState label="Loading AI Video Studio" />;
  if (config.isError) return <ErrorState error={config.error} retry={() => config.refetch()} />;
  return <section className="page video-studio-page">
    <header className="page-header"><div><span className="eyebrow">Local ComfyUI production</span><h1>AI Video Studio</h1><p>Turn one character reference and a short idea into an identity-consistent, versioned video asset.</p></div><div className="header-actions"><StatusBadge value={config.data?.comfyui || "UNKNOWN"} /><button className="button secondary" onClick={() => { config.refetch(); jobs.refetch(); }}><RefreshCw size={16} />Refresh</button></div></header>
    {!ready && <section className="panel image-capability-alert"><div><strong>Generation is safely unavailable</strong><p>{config.data?.comfyui === "READY" ? "No verified local video model and API workflow are available." : "The local ComfyUI API health check did not pass."}</p></div><div>{config.data?.missing_requirements?.map((item) => <span key={`${item.code}-${item.message}`} title={item.message}><b>{item.code}</b><small>{item.message}</small></span>)}</div></section>}
    <div className="tabbar">{[["studio", "Create"], ["batch", "Batch calendar"], ["progress", "Progress & preview"], ["library", "Asset library"]].map(([value, label]) => <button key={value} aria-selected={tab === value} onClick={() => setTab(value)}>{label}</button>)}</div>
    {tab === "studio" && <div className="video-studio-grid"><div className="panel studio-form"><div className="panel-heading"><div><span className="eyebrow">1 · Character memory</span><h2>Identity reference</h2></div><FileImage /></div><label>Saved character<select value={characterId} onChange={(event) => setCharacterId(event.target.value)}><option value="">Upload a character below</option>{characters.data?.map((item) => <option key={item.character_id} value={item.character_id}>{item.name} · v{item.version}</option>)}</select></label><div className="upload-box"><input aria-label="Character image" type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => setFile(event.target.files?.[0])} /><input placeholder="Character name" value={characterName} onChange={(event) => setCharacterName(event.target.value)} /><textarea placeholder="Recurring identity details: hairstyle, proportions, wardrobe, visual style…" value={identityNotes} onChange={(event) => setIdentityNotes(event.target.value)} /><button className="button secondary" disabled={!file || !characterName || upload.isPending} onClick={() => upload.mutate()}><Upload size={16} />Store identity</button>{upload.isError && <p className="inline-error">{upload.error.message}</p>}</div></div>
      <div className="panel studio-form"><div className="panel-heading"><div><span className="eyebrow">2 · Creative direction</span><h2>Recipe + idea</h2></div><WandSparkles /></div><label>Master recipe<select value={recipeId} onChange={(event) => setRecipeId(event.target.value)}>{config.data?.recipes.map((item) => <option key={item.recipe_id} value={item.recipe_id}>{item.name}</option>)}</select></label><label>Short idea<textarea rows={4} value={idea} onChange={(event) => setIdea(event.target.value)} placeholder="Serum advertisement in a sunlit minimal studio" /></label><div className="studio-options"><label>Model<select value={modelId} onChange={(event) => setModelId(event.target.value)}>{config.data?.models.filter((item) => item.enabled).map((item) => <option key={item.model_id} value={item.model_id}>{item.display_name}</option>)}</select></label><label>Duration<input type="number" min={1} max={20} value={duration} onChange={(event) => setDuration(Number(event.target.value))} /></label><label>Aspect ratio<select value={ratio} onChange={(event) => setRatio(event.target.value)}>{ratios.map((item) => <option key={item}>{item}</option>)}</select></label></div><label>Visual style<input value={style} onChange={(event) => setStyle(event.target.value)} /></label><label>Camera motion<input value={camera} onChange={(event) => setCamera(event.target.value)} /></label><button className="button primary studio-generate" disabled={!characterId || idea.trim().length < 2 || generate.isPending} onClick={() => generate.mutate()}><Play size={17} />Generate video</button>{generate.isError && <p className="inline-error">{generate.error.message}</p>}</div></div>}
    {tab === "batch" && <div className="video-studio-grid"><div className="panel studio-form"><span className="eyebrow">Automation ready</span><h2>Content calendar batch</h2><p className="muted">One idea per line. Each item becomes a durable script, prompt, GPU job, and asset.</p><label>Character<select value={characterId} onChange={(event) => setCharacterId(event.target.value)}><option value="">Select character</option>{characters.data?.map((item) => <option key={item.character_id} value={item.character_id}>{item.name}</option>)}</select></label><label>Ideas<textarea rows={12} value={batchIdeas} onChange={(event) => setBatchIdeas(event.target.value)} placeholder={"Serum launch teaser\nMorning routine product demo\nIngredient spotlight"} /></label><button className="button primary" disabled={!characterId || !batchIdeas.trim() || batch.isPending} onClick={() => batch.mutate()}><Layers3 size={16} />Queue batch</button>{batch.isError && <p className="inline-error">{batch.error.message}</p>}</div><div className="panel batch-summary"><Clapperboard /><h2>Monthly production</h2><strong>{batchIdeas.split("\n").filter((line) => line.trim()).length}</strong><span>videos ready to queue</span><p>Jobs run through the bounded GPU worker and keep their calendar IDs, prompts, identity checksum, model, version, and output metadata.</p></div></div>}
    {tab === "progress" && <div className="video-progress-layout"><div className="panel video-job-list"><div className="panel-heading"><h2>GPU queue</h2><span>{jobs.data?.length || 0} jobs</span></div>{jobs.data?.length ? jobs.data.map((job) => <button key={job.job_id} className={job.job_id === selectedJobId ? "active" : ""} onClick={() => setSelectedJobId(job.job_id)}><div><strong>{String(job.request.creative_idea || "Video")}</strong><StatusBadge value={job.status} /></div><span>{job.model?.display_name || "Routing…"} · {job.progress}%</span></button>) : <EmptyState title="No video jobs" />}</div><VideoPreview job={selectedJob} onRetry={(id) => retry.mutate(id)} onSave={(id) => save.mutate(id)} /></div>}
    {tab === "library" && <div className="asset-gallery">{jobs.data?.filter((job) => job.final_video).map((job) => <article className="panel" key={job.job_id}><video controls preload="metadata" src={videoStudioApi.previewUrl(job.final_video!)} /><div><Archive /><strong>{String(job.request.creative_idea || job.final_video!.filename)}</strong><span>{job.model?.display_name} · v{job.final_video!.version}</span><button className="button secondary" disabled={job.final_video!.saved} onClick={() => save.mutate(job.final_video!.asset_id)}>{job.final_video!.saved ? <Check size={15} /> : <Save size={15} />}{job.final_video!.saved ? "Saved" : "Save asset"}</button></div></article>)}{!jobs.data?.some((job) => job.final_video) && <div className="panel"><EmptyState title="No generated videos yet" detail="Completed renders appear here automatically, with every version and its generation metadata." /></div>}</div>}
  </section>;
}

function VideoPreview({ job, onRetry, onSave }: { job?: VideoJob; onRetry: (id: string) => void; onSave: (id: string) => void }) {
  if (!job) return <div className="panel"><EmptyState title="Select a video job" /></div>;
  return <div className="panel video-preview"><div className="panel-heading"><div><span className="eyebrow">{job.job_id}</span><h2>{String(job.request.creative_idea || "Video generation")}</h2></div><StatusBadge value={job.status} /></div><div className="video-stage">{job.final_video ? <video controls autoPlay muted loop src={videoStudioApi.previewUrl(job.final_video)} /> : <Clapperboard />}</div><div className="progress-body"><div className="progress-track"><i style={{ width: `${job.progress}%` }} /></div><strong>{job.progress}%</strong><p>{job.stage}</p>{job.error && <p className="inline-error"><b>{job.error.code}</b> / {job.error.message}</p>}<div className="run-actions">{job.status === "FAILED" && <button className="button secondary" onClick={() => onRetry(job.job_id)}><RefreshCw size={15} />Retry</button>}{job.final_video && <button className="button primary" disabled={job.final_video.saved} onClick={() => onSave(job.final_video!.asset_id)}><Save size={15} />{job.final_video.saved ? "Saved" : "Save asset"}</button>}</div><details><summary>Compiled prompt, script and identity constraints</summary><pre>{JSON.stringify(job.prompt_package, null, 2)}</pre></details></div></div>;
}
