from alembic import command
from alembic.runtime.migration import MigrationContext
from sqlalchemy import create_engine, inspect

from backend.db.migrations import (
    CURRENT_SCHEMA_REVISION,
    get_alembic_config,
    upgrade_database,
)


def test_database_migrations_upgrade_and_downgrade(tmp_path) -> None:
    database_file = tmp_path / "migration_test.db"
    database_url = f"sqlite+pysqlite:///{database_file.as_posix()}"
    upgrade_database(database_url)
    engine = create_engine(database_url)

    with engine.connect() as connection:
        revision = MigrationContext.configure(connection).get_current_revision()
    expected_tables = {
        "alembic_version",
        "system_meta",
        "creators",
        "platform_accounts",
        "creator_import_batches",
        "creator_import_errors",
        "content_items",
        "collection_runs",
        "analysis_runs",
        "content_segments",
        "content_shots",
        "analysis_results",
        "visual_events",
        "audio_events",
        "text_events",
        "content_dna",
        "performance_snapshots",
        "pattern_mining_runs",
        "patterns",
        "pattern_features",
        "pattern_content_links",
        "recipes",
        "recipe_versions",
        "recipe_pattern_links",
        "recipe_content_sources",
        "recipe_variants",
        "rules",
        "rule_versions",
        "rule_dependencies",
        "rule_sets",
        "rule_set_members",
        "rule_overrides",
        "rule_import_runs",
        "master_controls",
        "rule_evaluation_runs",
        "rule_evaluation_results",
        "human_review_requests",
        "generation_contracts",
        "generation_contract_versions",
        "rule_audit_logs",
        "provider_profiles",
        "model_profiles",
        "generation_jobs",
        "generation_attempts",
        "generation_events",
        "prompt_packages",
        "prompt_package_versions",
        "generated_assets",
        "asset_versions",
        "asset_references",
        "generation_qa_runs",
        "generation_qa_results",
        "generation_costs",
        "continuity_states",
        "storyboards",
        "storyboard_shots",
        "provenance_records",
        "products",
        "product_versions",
        "product_batches",
        "pricebooks",
        "pricebook_lines",
        "customers",
        "suppliers",
        "warehouses",
        "inventory_movements",
        "inventory_reservations",
        "stocktakes",
        "stocktake_lines",
        "sales_orders",
        "sales_order_lines",
        "sales_invoices",
        "sales_invoice_lines",
        "payments",
        "payment_allocations",
        "collection_activities",
        "purchase_orders",
        "purchase_order_lines",
        "goods_receipts",
        "goods_receipt_lines",
        "supplier_invoices",
        "supplier_payments",
        "sales_returns",
        "sales_return_lines",
        "territories",
        "sales_reps",
        "delivery_orders",
        "daily_closes",
        "msc_intake_batches",
        "msc_intake_files",
        "msc_invoice_staging",
        "accounting_journals",
        "accounting_journal_lines",
        "approval_requests",
        "business_events",
        "sales_audit_ledger",
        "messaging_contacts",
        "messaging_channel_accounts",
        "conversations",
        "messages",
        "message_attachments",
        "message_delivery_events",
        "conversation_states",
        "intent_results",
        "entity_extractions",
        "response_plans",
        "bot_decisions",
        "handoff_requests",
        "conversation_agent_notes",
        "message_edits",
        "followups",
        "marketing_consents",
        "crm_signals",
        "telesales_tasks",
        "quote_drafts",
        "order_drafts",
        "knowledge_items",
        "knowledge_versions",
        "response_templates",
        "template_versions",
        "conversation_summaries",
        "conversation_events",
        "messaging_webhook_events",
    }
    assert revision == CURRENT_SCHEMA_REVISION
    assert expected_tables == set(inspect(engine).get_table_names())

    command.downgrade(get_alembic_config(database_url), "base")
    assert set(inspect(engine).get_table_names()) <= {"alembic_version"}
    engine.dispose()
