"""Import every ORM model so migrations receive complete metadata."""

from backend.db.models.content_item import ContentItem
from backend.db.models.collection_run import CollectionRun
from backend.db.models.creator import Creator
from backend.db.models.import_batch import CreatorImportBatch, CreatorImportError
from backend.db.models.platform_account import PlatformAccount
from backend.db.models.system_meta import SystemMeta
from backend.db.models.pattern_recipe import (
    ContentDNA,
    Pattern,
    PatternContentLink,
    PatternFeature,
    PatternMiningRun,
    PerformanceSnapshot,
    Recipe,
    RecipeContentSource,
    RecipePatternLink,
    RecipeVariant,
    RecipeVersion,
)
from backend.db.models.rules import (
    GenerationContract,
    GenerationContractVersion,
    HumanReviewRequest,
    MasterControl,
    Rule,
    RuleDependency,
    RuleEvaluationResult,
    RuleEvaluationRun,
    RuleImportRun,
    RuleAuditLog,
    RuleOverride,
    RuleSet,
    RuleSetMember,
    RuleVersion,
)
from backend.db.models.generation import (
    AssetReference,
    AssetVersion,
    ContinuityState,
    GeneratedAsset,
    GenerationAttempt,
    GenerationCostRecord,
    GenerationEvent,
    GenerationJob,
    GenerationQARun,
    GenerationQAResult,
    ModelProfile,
    PromptPackage,
    PromptPackageVersion,
    ProviderProfile,
    ProvenanceRecord,
    Storyboard,
    StoryboardShot,
)
from backend.db.models.sales import (
    AccountingJournal, AccountingJournalLine, ApprovalRequest, AuditLedger,
    BusinessEvent, CollectionActivity, Customer, DailyClose, Delivery,
    GoodsReceipt, GoodsReceiptLine, InventoryMovement, InventoryReservation,
    MscIntakeBatch, MscIntakeFile, MscInvoiceStaging, Payment,
    PaymentAllocation, PriceBook, PriceBookLine, Product, ProductBatch,
    ProductVersion, PurchaseOrder, PurchaseOrderLine, SalesInvoice,
    SalesInvoiceLine, SalesOrder, SalesOrderLine, SalesRep, SalesReturn,
    SalesReturnLine, Stocktake, StocktakeLine, Supplier, SupplierInvoice,
    SupplierPayment, Territory, Warehouse,
)
from backend.db.models.answer_bot import (
    AgentNote, BotDecision, ChannelAccount, Contact, Conversation,
    ConversationEvent, ConversationState, ConversationSummary, CRMSignal,
    EntityExtraction, FollowUp, HandoffRequest, IntentResult, KnowledgeItem,
    KnowledgeVersion, MarketingConsent, Message, MessageAttachment,
    MessageDeliveryEvent, MessageEdit, OrderDraft, QuoteDraft, ResponsePlan,
    ResponseTemplate, TelesalesTask, TemplateVersion, WebhookEvent,
)

__all__ = [
    "AnalysisResult",
    "AnalysisRun",
    "AudioEvent",
    "ContentItem",
    "CollectionRun",
    "ContentSegment",
    "ContentShot",
    "Creator",
    "CreatorImportBatch",
    "CreatorImportError",
    "PlatformAccount",
    "SystemMeta",
    "TextEvent",
    "VisualEvent",
    "ContentDNA",
    "Pattern",
    "PatternContentLink",
    "PatternFeature",
    "PatternMiningRun",
    "PerformanceSnapshot",
    "Recipe",
    "RecipeContentSource",
    "RecipePatternLink",
    "RecipeVariant",
    "RecipeVersion",
    "Rule",
    "RuleVersion",
    "RuleDependency",
    "RuleSet",
    "RuleSetMember",
    "RuleOverride",
    "RuleImportRun",
    "RuleAuditLog",
    "MasterControl",
    "RuleEvaluationRun",
    "RuleEvaluationResult",
    "HumanReviewRequest",
    "GenerationContract",
    "GenerationContractVersion",
    "ProviderProfile",
    "ModelProfile",
    "GenerationJob",
    "GenerationAttempt",
    "GenerationEvent",
    "PromptPackage",
    "PromptPackageVersion",
    "GeneratedAsset",
    "AssetVersion",
    "AssetReference",
    "GenerationQARun",
    "GenerationQAResult",
    "GenerationCostRecord",
    "ContinuityState",
    "Storyboard",
    "StoryboardShot",
    "ProvenanceRecord",
    "Product", "ProductVersion", "ProductBatch", "PriceBook", "PriceBookLine",
    "Customer", "Supplier", "Warehouse", "InventoryMovement",
    "InventoryReservation", "Stocktake", "StocktakeLine", "SalesOrder",
    "SalesOrderLine", "SalesInvoice", "SalesInvoiceLine", "Payment",
    "PaymentAllocation", "CollectionActivity", "PurchaseOrder",
    "PurchaseOrderLine", "GoodsReceipt", "GoodsReceiptLine", "SupplierInvoice",
    "SupplierPayment", "SalesReturn", "SalesReturnLine", "Territory", "SalesRep",
    "Delivery", "DailyClose", "MscIntakeBatch", "MscIntakeFile",
    "MscInvoiceStaging", "AccountingJournal", "AccountingJournalLine",
    "ApprovalRequest", "BusinessEvent", "AuditLedger",
    "Contact", "ChannelAccount", "Conversation", "Message",
    "MessageAttachment", "MessageDeliveryEvent", "ConversationState",
    "IntentResult", "EntityExtraction", "ResponsePlan", "BotDecision",
    "HandoffRequest", "AgentNote", "MessageEdit", "FollowUp",
    "MarketingConsent", "CRMSignal", "TelesalesTask", "QuoteDraft",
    "OrderDraft", "KnowledgeItem", "KnowledgeVersion", "ResponseTemplate",
    "TemplateVersion", "ConversationSummary", "ConversationEvent",
    "WebhookEvent",
]
from backend.db.models.analysis import (
    AnalysisResult,
    AnalysisRun,
    AudioEvent,
    ContentSegment,
    ContentShot,
    TextEvent,
    VisualEvent,
)
