"""Schema and evidence map extracted from the Creator Intelligence master workbook."""

from __future__ import annotations

from typing import Literal


TEMPLATE_SHEETS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("01_Creator_Master_Database", ("Creator_ID", "Real_Name", "Creator_Name", "All_Usernames", "Country", "City", "Language", "Start_Year", "First_Platform", "First_Content", "Current_Status", "YouTube", "Facebook", "Instagram", "TikTok_MusicalLy", "Snapchat", "LinkedIn", "Blog", "Podcast")),
    ("02_Creator_History_2014_NOW", ("Year", "Event", "Platform", "Content_Shift", "Growth_Point", "Major_Moment", "Industry_Impact")),
    ("03_Content_Archive", ("Content_ID", "Creator", "Platform", "Date", "Title", "URL", "Format", "Topic", "Views", "Likes", "Comments", "Shares", "Saves", "Performance")),
    ("04_Video_Forensic_Analysis", ("Video", "Hook_0_3_sec", "Story_Structure", "Angle", "Retention_Mechanism", "Camera", "Lens", "Lighting", "Editing", "Sound", "CTA", "Why_Viral")),
    ("05_Transcript_Conversation_Engine", ("Video", "Timestamp", "Speaker", "Exact_Words", "Language", "Question", "Answer", "Emotion", "Key_Quote", "Topic")),
    ("06_Creator_DNA", ("Personality", "Voice", "Tone", "Presentation", "Storytelling_Style", "Visual_Identity", "Editing_Style", "Audience_Relationship", "Success_Formula")),
    ("07_Audience_Intelligence", ("Persona", "Age", "Location", "Needs", "Pain_Points", "Motivation", "Behavior", "Questions", "Triggers")),
    ("08_Strategy_Engine", ("Mission", "Vision", "Positioning", "USP", "Benchmark", "Differentiation")),
    ("09_Content_Pillars", ("Pillar", "Percentage", "Goal", "Examples")),
    ("10_Idea_Generation_Engine", ("Idea", "Problem", "Angle", "Trigger", "Hook", "Platform", "Format")),
    ("11_Hook_Database", ("Hook", "Type", "Psychological_Trigger", "Industry", "Example", "Performance")),
    ("12_Storytelling_Engine", ("Story_Type", "Hero_Journey", "PAS", "BAB", "Conflict", "Transformation", "Emotion")),
    ("13_Script_Engine", ("Scene", "Duration", "Visual", "Voice_Over", "Dialogue", "Camera_Direction", "Emotion", "CTA")),
    ("14_Copywriting_Engine", ("Framework", "Headline", "Caption", "Sales_Copy", "AIDA", "PAS", "FAB", "4U")),
    ("15_Art_Direction", ("Moodboard", "Style", "Colors", "Composition", "Camera", "Lens", "Lighting", "References")),
    ("16_AI_Prompt_Engine", ("Subject", "Action", "Environment", "Camera", "Motion", "Style", "Quality", "Resolution", "Negative_Prompt")),
    ("17_UGC_Engine", ("Creator", "Product", "Problem", "Experience", "Proof", "Reaction", "CTA")),
    ("18_Platform_Algorithm", ("Platform", "Ranking_Factors", "CTR", "Retention", "Watch_Time", "Completion", "Rewatch", "Shares", "Saves")),
    ("19_Analytics_KPI", ("Reach", "Views", "Engagement", "Growth", "Conversion", "ROI", "ROAS")),
    ("20_Media_Buying", ("Objective", "Audience", "Creative", "Budget", "CPM", "CPC", "CPA", "ROAS")),
    ("21_Creative_Testing", ("Variable", "Hook", "Thumbnail", "CTA", "Length", "Music", "Result")),
    ("22_Trend_Event_Intelligence", ("Trend", "Date", "Platform", "Origin", "Impact", "Opportunity")),
    ("23_SEO_Search_Intelligence", ("Keyword", "Intent", "Title", "Description", "Tags", "Ranking")),
    ("24_Community_Management", ("Comments", "FAQ", "Sentiment", "Crisis", "Community_Growth")),
    ("25_AI_Agent_Commands", ("Command_ID", "Agent", "Input", "Instruction", "Data_Needed", "Processing", "Output")),
    ("26_Output_Report_Structure", ("Report", "Sections", "Fields", "Final_Result")),
    ("27_Data_Source_Collection", ("Source", "Platform", "Collection_Method", "Data_Type")),
    ("28_Content_Repurposing", ("Original", "Shorts", "Reels", "TikTok", "Blog", "X", "LinkedIn", "Carousel")),
    ("29_Creator_Monetization", ("Brand_Deals", "Products", "Services", "Affiliate", "Revenue_Model")),
    ("30_Final_Creator_Intelligence_Report", ("Finding", "Evidence", "Analysis", "Recommendation")),
    ("31_Output_Creator_Master_Profile", ("Creator_ID", "Real_Name", "Creator_Name", "Username", "Account_Type", "Country", "City", "Language", "Age_Group", "Main_Field", "Sub_Field")),
    ("32_Output_Origin_Story", ("Start_Date", "First_Appearance", "First_Platform", "First_Video", "First_Idea", "Reason_Started", "Previous_Work", "Hobby_To_Professional_Journey")),
    ("33_Output_Complete_Timeline", ("Year", "Event", "Platform", "Content_Type", "Audience_Size", "Transformation", "Videos", "Awards", "Collaborations", "Crises", "Development")),
    ("34_Output_Platform_Audit", ("Platform", "Account_URL", "Creation_Date", "Followers", "Subscribers", "Total_Views", "Average_Views", "Top_Content", "Lowest_Content", "Posting_Frequency", "Best_Topics")),
    ("35_Output_Content_Inventory", ("Content_ID", "Title", "URL", "Platform", "Date", "Duration", "Format", "Topic", "Views", "Likes", "Comments", "Shares", "Saves", "Engagement_Rate")),
    ("36_Output_Top_Performing_Content", ("Ranking", "Content", "Views", "Shares", "Comments", "Saves", "Retention", "Why_Successful", "Hook", "Story", "Emotion", "Trend")),
    ("37_Output_Content_Classification", ("Educational", "Entertainment", "Storytelling", "Review", "Reaction", "Documentary", "Vlog", "Podcast", "Tutorial", "Challenge")),
    ("38_Output_Content_DNA", ("Personality", "Voice", "Energy", "Presentation", "Editing_Style", "Visual_Identity", "Audience_Relationship", "Success_Formula")),
    ("39_Output_Audience_Analysis", ("Age", "Gender", "Country", "Interests", "Problems", "Needs", "Behavior", "Interaction_Time", "Audience_Type")),
    ("40_Output_Buyer_Persona", ("Persona_Name", "Age", "Job", "Problems", "Fears", "Desires", "Motivations", "Objections", "Follow_Reason")),
    ("41_Output_Content_Strategy", ("Positioning", "USP", "Mission", "Vision", "Values", "Differentiation")),
    ("42_Output_Hook_Analysis", ("Text_Hook", "Visual_Hook", "Audio_Hook", "Hook_Type", "Curiosity", "Problem", "Benefit", "Shock", "Story", "Pattern_Interrupt")),
    ("43_Output_Storytelling", ("Hero_Journey", "Before_After", "PAS", "BAB", "Transformation", "Character", "Conflict", "Solution", "Emotion")),
    ("44_Output_Video_Deconstruction", ("Hook", "Introduction", "Body", "Ending", "Shot_Type", "Camera_Angle", "Composition", "Lens", "Movement", "Cuts", "Transitions", "Captions", "Music", "Sound_Effects")),
    ("45_Output_AI_Video_Prompts", ("Subject", "Action", "Environment", "Camera", "Lens", "Lighting", "Motion", "Style", "Quality", "Resolution", "Negative_Prompt")),
    ("46_Output_Image_Prompts", ("Prompt", "Style", "Camera", "Lens", "Lighting", "Composition", "Aspect_Ratio", "Negative_Prompt")),
    ("47_Output_Script_Generation", ("Scene", "Visual", "Voice_Over", "Dialogue", "Camera_Direction", "Emotion", "Duration", "CTA")),
    ("48_Output_UGC_Analysis", ("Recording_Style", "Creator_Persona", "Trust", "Problem", "Solution", "Proof", "Reaction", "CTA")),
    ("49_Output_Copywriting", ("AIDA", "PAS", "FAB", "4U", "Headline", "Caption", "Sales_Copy", "CTA")),
    ("50_Output_CTA_Database", ("CTA", "Type", "Goal", "Platform", "Engagement", "Lead", "Sales", "Follow", "Subscribe")),
    ("51_Video_Copywriting_Archive", ("Video_ID", "Creator", "Platform", "Video_URL", "Publish_Date", "Video_Title", "Caption_Copy", "Description_Copy", "Hashtags", "Opening_Text", "Main_Copy", "Closing_Copy", "CTA_Copy", "Copy_Type", "Copy_Framework", "Tone_of_Voice", "Persuasive_Elements")),
    ("52_Video_By_Video_Full_Analysis", ("Video_ID", "Hook", "Visual_Hook", "Spoken_Hook", "Story_Type", "Script_Summary", "Full_Transcript", "Scene_Count", "Scene_By_Scene", "Camera_Direction", "Editing_Style", "Transitions", "Music", "Sound_Effects", "Visual_Style", "Audience_Trigger", "Why_Performed")),
    ("53_Video_Copy_Reverse_Engineering", ("Video_ID", "Original_Idea", "Angle", "Target_Audience", "Problem", "Promise", "Value_Delivery", "Emotional_Trigger", "Persuasion_Method", "CTA_Strategy", "Replicable_Formula")),
    ("54_Content_Recreation_Engine", ("Original_Video", "New_Content_Idea", "New_Hook", "New_Script", "New_Copy", "New_Visual_Direction", "New_AI_Video_Prompt", "Platform_Adaptation")),
    ("55_FULL_CONVERSATION_AUDIT_COMMANDS", ("Command_ID", "Source_Section", "Extraction_Target", "Required_Action", "Input", "Analysis_Method", "Output")),
    ("56_COMPLETE_COPYWRITING_ENGINE", ("Content_ID", "Original_Copy", "Hook_Copy", "Headline", "Caption", "Body_Copy", "CTA", "Framework", "AIDA", "PAS", "FAB", "4U", "Tone", "Emotion", "Persuasion_Trigger", "Conversion_Goal")),
    ("57_CREATOR_COMPLETE_COMMAND_PIPELINE", ("Step", "Agent", "Task", "Input_Data", "Processing", "Final_Output")),
    ("58_VIDEO_TRANSCRIPT_INTELLIGENCE", ("Video_ID", "Full_Text", "Speaker", "Timestamp", "Important_Quotes", "Questions", "Answers", "Story_Moments", "Emotional_Points")),
    ("59_CONTENT_MACHINE_MASTER_OUTPUT", ("Creator_Profile", "History", "Platforms", "Content_DNA", "Videos", "Scripts", "Copy", "Stories", "Visuals", "Ads", "Analytics", "Replication_Model")),
    ("60_NOTEBOOK_COMMAND_EXTRACTION", ("Command_ID", "Notebook_Concept", "Required_Extraction", "Machine_Action", "Expected_Output")),
    ("61_CONTENT_MACHINE_ARCHITECTURE", ("Layer", "Component", "Purpose", "Input", "Processing", "Output")),
    ("62_SOCIAL_MEDIA_INTELLIGENCE_ENGINE", ("Platform", "Analysis_Point", "Metrics", "Content_Factors", "Optimization_Output")),
    ("63_USER_EXPERIENCE_CONTENT_ENGINE", ("User_Experience", "User_Journey", "Pain_Point", "Interaction", "Improvement_Action")),
    ("64_EGC_UGC_WOM_ENGINE", ("Content_Type", "Creator_Source", "Community_Signal", "Word_of_Mouth_Factor", "Analysis")),
    ("65_CONTENT_RECOMMENDATION_AI_ENGINE", ("Data_Input", "Recommendation_Type", "AI_Action", "Reasoning", "Final_Suggestion")),
    ("66_WORLD_OF_MARKETING_ENGINE", ("Marketing_Element", "Framework", "Application", "Content_Output")),
    ("67_COPYWRITING_DEEP_ANALYSIS", ("Copy_Element", "Headline", "Hook", "Message", "Emotion", "Persuasion", "CTA")),
    ("68_HIDDEN_MESSAGES_ANALYSIS", ("Content", "Hidden_Message", "Psychology", "Audience_Impact", "Brand_Meaning")),
    ("69_CREATIVE_STRATEGY_ENGINE", ("Creative_Idea", "Concept", "Execution", "Visual_Direction", "Expected_Result")),
    ("70_VIDEO_QUALITY_ENGINE", ("Video_Element", "Resolution", "Visual_Quality", "Editing", "Production_Notes")),
    ("71_PLATFORM_OPTIMIZATION_COMMANDS", ("Platform", "Publishing_Rules", "Algorithm_Factors", "Optimization_Command")),
    ("72_OPERATION_COMMANDS_MASTER", ("Command_ID", "Command_Name", "Agent", "Purpose", "Input_Data", "Processing_Instructions", "Analysis_Method", "Required_Fields", "Output_Result", "Validation_Check")),
)


FieldSource = Literal["API", "DATABASE", "AI_ANALYSIS", "CALCULATED", "UNAVAILABLE"]

# Workbook-level lineage map. Fields not supported by collected evidence remain UNKNOWN.
FIELD_SOURCE_MAP: dict[str, FieldSource] = {
    "identity": "DATABASE",
    "profile_metrics": "API",
    "content_archive": "API",
    "engagement_rate": "CALCULATED",
    "top_content": "CALCULATED",
    "posting_frequency": "CALCULATED",
    "industry_niche": "AI_ANALYSIS",
    "content_dna": "AI_ANALYSIS",
    "audience_interests": "AI_ANALYSIS",
    "strategy_recommendations": "AI_ANALYSIS",
    "camera_lens_lighting": "UNAVAILABLE",
    "transcripts": "UNAVAILABLE",
    "audience_demographics": "UNAVAILABLE",
    "conversion_roi_roas": "UNAVAILABLE",
}

IMPORTANT_SHEETS = frozenset({
    "01_Creator_Master_Database", "03_Content_Archive", "06_Creator_DNA",
    "07_Audience_Intelligence", "08_Strategy_Engine", "09_Content_Pillars",
    "10_Idea_Generation_Engine", "11_Hook_Database", "18_Platform_Algorithm",
    "19_Analytics_KPI", "22_Trend_Event_Intelligence", "24_Community_Management",
    "27_Data_Source_Collection", "30_Final_Creator_Intelligence_Report",
    "31_Output_Creator_Master_Profile", "34_Output_Platform_Audit",
    "35_Output_Content_Inventory", "36_Output_Top_Performing_Content",
    "37_Output_Content_Classification", "38_Output_Content_DNA",
    "39_Output_Audience_Analysis", "40_Output_Buyer_Persona",
    "41_Output_Content_Strategy", "42_Output_Hook_Analysis",
    "44_Output_Video_Deconstruction", "49_Output_Copywriting",
    "50_Output_CTA_Database", "51_Video_Copywriting_Archive",
    "52_Video_By_Video_Full_Analysis", "53_Video_Copy_Reverse_Engineering",
    "57_CREATOR_COMPLETE_COMMAND_PIPELINE", "59_CONTENT_MACHINE_MASTER_OUTPUT",
    "62_SOCIAL_MEDIA_INTELLIGENCE_ENGINE", "65_CONTENT_RECOMMENDATION_AI_ENGINE",
    "69_CREATIVE_STRATEGY_ENGINE", "71_PLATFORM_OPTIMIZATION_COMMANDS",
})

